FROM pcentos7:7.4.1708
RUN yum -y install yum-utils && \
    yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum-config-manager --enable remi-php72 && \
    yum -y update && yum -y install php php-pgsql && \
    rm -rf /var/www/html/*
COPY src/www_root /var/www/html/
COPY src/lib/ /var/www/lib/
COPY src/resources/ /var/www/resources/
EXPOSE 80
ENV KONTTI_HOST kontti_db
ENV KONTTI_PORT 5432
ENV KONTTI_DB kontti
ENV KONTTI_USER kontti
ENV KONTTI_PASSWORD konttipassu
CMD [ "/usr/sbin/httpd", "-DFOREGROUND" ]
