version: 2.0
services:
  dbpostgres:
    image: postgres:latest
    volumes:
      - postgres-db-volume:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
  web:
    image: php:7.2-apache
    links:
      - ddbpostgres
    ports:
      - 8080:8080
    depends_on:
      - dbpostgres

volumes:
  postgres-db-volume: