FROM pcentos7:7.4.1708
RUN yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum install update && yum -y install php php-pgsql
run rm -rf /var/www/html/*
COPY src/www_root /var/www/html/
COPY src/lib/ /var/www/lib/
COPY src/resources/ /var/www/resources/
EXPOSE 80
CMD [ "systemctl" "start" "httpd"]